package guru.springframework.sfgpetclinic;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;
// TODO 76.
public class CustomArgsProvider implements ArgumentsProvider {


    //The below provideArguments method was generated by cmd + N > implement methods because initially CustomArgsProvider was not happy
    // Then we added the return ourselves
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) throws Exception {
        return Stream.of(Arguments.of("Fl", 7, 1), Arguments.of("OH", 11, 42), Arguments.of("MI", 44, 77));
    }
}
